apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/devfile-sample/devfile-sample@sha256:bca5deff323b693b6f19ce3d50311a447d29973416deb74e2db532ad2d2c7e9c
        name: my-nodejs
        resources: {}
status: {}
